export const HOME_PAGE = "/home";
export const MENU_PAGE = "/home/:id";
export const JOBS_PAGE = "/jobs";
export const ABOUT_PAGE = "/about";
export const CONTACT_PAGE= "/contact";
export const PROJECT_PAGE = "/project";
export const BASKET_PAGE = "/basket";
export const LOGIN_PAGES ="/login";
export const RESET_PASSWORD="/resetpassword";
export const NEW_PASSWORD="/newpassword";
export const REGISTER_PAGE="/registration";
export const PROFIL_PAGE="/profile";
export const PROJECT_PAGE_INFO="/project/:id"
export const FOOD_TRUCK_PAGE="/foodtruck";
export const GRAND_BUFFE_PAGE ="/buffet/:id";
export const SEARCH_PAGE = "/search";
export const PRIVACY_POLICEY="/privacy_policy";